package adventofcode2024;

import static org.assertj.core.api.Assertions.assertThat;

import java.util.HashSet;

import org.junit.jupiter.api.Test;

import adventofcode2024.Day8.Map;

class Day8Test {

	@Test
	void test() {
		Map map = Day8.Map.parse("""
				..........
				...#......
				..........
				....a.....
				..........
				.....a....
				..........
				......#...
				..........
				..........
				""");
		System.out.println("Part1:");
		map.printOn(System.out);
		System.out.println();
		var antiNodes = map.findAntiNodes();
		assertThat(antiNodes).isEqualTo(map.frequencyPositions.get('#'));
	}
	@Test
	void testPart2() {
		Map map = Day8.Map.parse("""
				T....#....
				...T......
				.T....#...
				.........#
				..#.......
				..........
				...#......
				..........
				....#.....
				..........
				""");
		System.out.println("Part1:");
		map.printOn(System.out);
		System.out.println();
		var antiNodes = map.findAntiNodesWithResonantHarmonics();
		HashSet<Point> parsedAntiNodes = map.frequencyPositions.get('#');
		parsedAntiNodes.addAll(map.frequencyPositions.get('T'));
		assertThat(antiNodes).isEqualTo(parsedAntiNodes);
	}
}
